import type { Metadata } from "next";

import { LegalPage } from "@/components/legal/legal-page";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Política de privacidade", description: "Saiba quais dados a Atlas Móveis coleta, por que os utiliza, com quem os compartilha e como exercer seus direitos." };

export default function PrivacyPage() {
  return <LegalPage
    title="Política de privacidade"
    intro="Esta política explica, de forma prática, como a Atlas Móveis trata dados pessoais durante a navegação, criação de conta, atendimento e compra. Usamos os dados necessários para operar a loja, cumprir o pedido e atender obrigações legais; não vendemos dados pessoais."
    references={[{ label: "Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018)", href: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm" }, { label: "Direitos dos titulares de dados (ANPD)", href: "https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados" }]}
    sections={[
      { title: "Quem trata seus dados e como falar conosco", paragraphs: ["A Atlas Móveis é responsável pelas decisões sobre o tratamento de dados feito na operação da loja. Para dúvidas, solicitações ou exercício dos seus direitos, escreva para " + siteConfig.email + " ou entre em contato pelo WhatsApp comercial informado no site. Inclua um meio de retorno; poderemos solicitar informações estritamente necessárias para confirmar sua identidade e proteger sua conta."] },
      { title: "Quais dados podemos coletar", paragraphs: ["Os dados variam conforme o que você faz no site. Não pedimos todos os dados em todas as etapas."], bullets: ["Conta e identificação: nome, e-mail, telefone e identificador da conta. A credencial é gerida pelo serviço de autenticação; a loja não acessa sua senha em texto claro.", "Compra e emissão fiscal: CPF ou CNPJ; quando informado para cadastro empresarial, razão social, nome fantasia e inscrições estadual ou municipal.", "Entrega e contato: CEP, rua, número, complemento, bairro, cidade, UF e observações fornecidas por você.", "Pedido: produtos e quantidades, modalidade de compra, valores, desconto, frete, forma e situação do pagamento, endereço de entrega e histórico de atendimento.", "Navegação e segurança: dados técnicos necessários à sessão, autenticação, prevenção de abuso e funcionamento do carrinho. O carrinho pode ficar armazenado no navegador para que os itens persistam entre visitas."] },
      { title: "Para que usamos os dados", paragraphs: ["Tratamos os dados para finalidades determinadas e compatíveis com a operação da loja, incluindo:"], bullets: ["Criar e proteger sua conta, autenticar seu acesso e prestar suporte.", "Validar disponibilidade, preço, estoque, desconto e frete; registrar o pedido e acompanhar seu processamento e entrega.", "Encaminhar ao Mercado Pago os dados necessários à criação do checkout e à confirmação do pagamento.", "Consultar cotações logísticas e viabilizar a entrega pelo Melhor Envio ou pela modalidade própria disponível para Curitiba/PR.", "Cumprir obrigações fiscais, contábeis, consumeristas e regulatórias; responder a solicitações legítimas de autoridades.", "Investigar fraude, proteger pessoas e sistemas, resolver disputas e manter registros de auditoria e segurança."] },
      { title: "Bases legais e dados fiscais", paragraphs: ["Conforme a finalidade, o tratamento pode ser necessário para executar medidas pré-contratuais e o contrato de compra, cumprir obrigação legal ou regulatória, exercer direitos, proteger o crédito ou atender interesse legítimo com respeito aos seus direitos. Quando uma atividade depender de consentimento, ele será solicitado de forma específica e poderá ser revogado, sem afetar tratamentos já realizados legitimamente.", "CPF/CNPJ e dados cadastrais podem ser necessários para identificar o comprador, processar o pagamento, atender regras fiscais e emitir documentos fiscais quando aplicável. Fornecer dados incorretos pode impedir a conclusão da compra ou a emissão correta do documento."] },
      { title: "Com quem os dados podem ser compartilhados", paragraphs: ["Compartilhamos apenas o necessário com fornecedores que viabilizam a operação, sujeitos às suas próprias condições e medidas de segurança:"], bullets: ["Supabase: autenticação, banco de dados e armazenamento técnico da aplicação.", "Mercado Pago: criação do checkout, processamento e retorno do estado do pagamento. Os dados de pagamento são tratados no ambiente do provedor; a Atlas Móveis não recebe os dados completos do cartão.", "Melhor Envio: CEP de destino e características dos volumes são enviados para a cotação. Dados de contato e endereço podem ser compartilhados com a transportadora quando necessários para efetivar a entrega.", "Autoridades, órgãos fiscais, judiciais ou reguladores, quando houver obrigação legal ou ordem válida."] },
      { title: "Pagamentos e segurança", paragraphs: ["O site recalcula os valores do pedido no servidor a partir do catálogo, das quantidades e da modalidade escolhida; o valor exibido no navegador não é a fonte de autoridade do pagamento. Os dados de cartão não devem ser enviados por e-mail, WhatsApp ou observações do pedido. A Atlas Móveis não os solicita nesses canais.", "Adotamos controles de acesso, autenticação e medidas técnicas e organizacionais adequadas ao porte e aos riscos da operação. Nenhum serviço conectado à internet pode prometer segurança absoluta; se identificarmos incidente relevante envolvendo dados pessoais, adotaremos as providências legais e comunicaremos os afetados e a autoridade quando exigido."] },
      { title: "Armazenamento, retenção e transferências", paragraphs: ["Mantemos os dados pelo tempo necessário para cumprir as finalidades informadas, manter a conta e o histórico do pedido, atender prazos legais e fiscais, prevenir fraude e exercer ou defender direitos. Depois disso, os dados serão eliminados ou anonimizados quando possível, ressalvadas hipóteses legais de conservação.", "Os fornecedores podem processar dados em infraestrutura localizada fora do Brasil. Quando houver transferência internacional, ela deverá observar as exigências e salvaguardas previstas na legislação brasileira."] },
      { title: "Seus direitos e cookies", paragraphs: ["Nos termos da LGPD, você pode solicitar confirmação e acesso, correção, informação sobre compartilhamentos, anonimização, bloqueio ou eliminação de dados excessivos ou tratados em desconformidade, portabilidade quando aplicável, revisão de decisões automatizadas e informações sobre consentimento e sua revogação. Alguns pedidos podem ser limitados por obrigações legais ou pela necessidade de conservar registros; explicaremos o motivo.", "O navegador pode guardar dados técnicos de sessão e o conteúdo do carrinho. Bloquear o armazenamento essencial pode prejudicar login, segurança ou recuperação do carrinho. Você pode gerenciar cookies e dados locais nas configurações do navegador; a remoção pode encerrar sessões e apagar itens salvos."] },
      { title: "Atualizações desta política", paragraphs: ["Podemos revisar este texto para refletir mudanças na loja, nos fornecedores ou na legislação. A versão vigente ficará publicada nesta página com a data de atualização. Mudanças relevantes serão comunicadas pelos canais disponíveis quando apropriado."] }
    ]}
  />;
}
